server:
  port: 9090

spring:
  application:
    name: api-gateway-park
  config:
    import: "optional:configserver:http://config-server-park:8888"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
