spring:
  application:
    name: tickets-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/tickets_db

  config:
    import: "optional:configserver:http://config-server-park:8888"

  jpa:
    hibernate:
      ddl-auto: create-drop

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: tickets-service-group

server:
  port: 8083

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
