spring:
  application:
    name: games-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/games_db

  config:
    import: "optional:configserver:http://config-server-park:8888"

  jpa:
    hibernate:
      ddl-auto: create-drop

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: games-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"


server:
  port: 8082

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

