spring:
  application:
    name: employees-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/employees_db

  config:
    import: "optional:configserver:http://config-server-park:8888"

  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8081

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
