spring:
  application:
    name: buyer-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/buyer_db

  config:
    import: "optional:configserver:http://config-server-park:8888"

  jpa:
    hibernate:
      ddl-auto: create-drop

  cache:
    type: redis
    redis:
      host: localhost
      port: 6379

server:
  port: 8084

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.data.redis: TRACE
    org.springframework.cache.interceptor: TRACE


