server:
  port: 8761

spring:
  application:
    name: eureka-server-park
  config:
    import: "optional:configserver:http://config-server-park:8888"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false